- id: '1714266514918'
  alias: Turn off guest bathroom fan
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: cec6cf7b7945ee752fbbee055f301b57
    entity_id: 2e8a2e9950a01569e2f02fd808ec5ca7
    domain: switch
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: cec6cf7b7945ee752fbbee055f301b57
    entity_id: 2e8a2e9950a01569e2f02fd808ec5ca7
    domain: switch
  mode: single
- id: '1715823252368'
  alias: Person Detected
  description: ''
  triggers:
  - device_id: 9df6f65a180173f2e3633563e9e78047
    domain: lock
    entity_id: 43095006648c911697d4fe9b4dbb64bb
    type: unlocked
    trigger: device
  conditions:
  - condition: sun
    after: sunset
    before: sunrise
  - condition: time
    before: '23:59:00'
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
    after: 09:00:00
    enabled: false
  actions:
  - type: turn_on
    device_id: d9a69c3898b4a309509f2800abf53d0d
    entity_id: 29045bf1514d3c1eda019ca4216ddbbf
    domain: switch
  - type: turn_on
    device_id: 01573fd33c66a99af92bf70d0f2a5e73
    entity_id: 2110dadfbb1c0284563e54b5cdd629e4
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: d9a69c3898b4a309509f2800abf53d0d
    entity_id: 29045bf1514d3c1eda019ca4216ddbbf
    domain: switch
  - type: turn_off
    device_id: 01573fd33c66a99af92bf70d0f2a5e73
    entity_id: 2110dadfbb1c0284563e54b5cdd629e4
    domain: switch
  mode: single
- id: '1716588637180'
  alias: Light-up the gym!
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 68fd9f430f8b6f19e874e6c8b34f7dba
    entity_id: 8aaeb3c0cbfbd2d25ec7fd81c7e24024
    domain: switch
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 255
      - 48
      - 48
      brightness_pct: 100
    target:
      device_id:
      - dbc728395fa7aa2768891fc2cbbe3d10
      - bcaa38844f0f0127d67dc79dea1c4e8e
  mode: single
- id: '1716588692455'
  alias: Gym off
  description: ''
  triggers:
  - type: turned_off
    device_id: 68fd9f430f8b6f19e874e6c8b34f7dba
    entity_id: 8aaeb3c0cbfbd2d25ec7fd81c7e24024
    domain: switch
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data:
      brightness_pct: 100
      rgb_color:
      - 255
      - 251
      - 43
    target:
      device_id:
      - dbc728395fa7aa2768891fc2cbbe3d10
      - bcaa38844f0f0127d67dc79dea1c4e8e
    action: light.turn_on
  - action: rest_command.call_my_url
    data: {}
  mode: single
- id: '1719814423724'
  alias: Bedroom temp
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: '0'
  conditions:
  - type: is_temperature
    condition: device
    device_id: f1e00c9150893aa8738c825238cd2dbe
    entity_id: e0c7e24fe55107c937030ca65c61b4b7
    domain: sensor
    below: 21
  actions:
  - device_id: 86a7dbedc6147e846661d1173576234a
    domain: mobile_app
    type: notify
    message: 'Bedroom temperature is: {{ states(''sensor.indoor_outdoor_meter_0c3f'',
      with_unit=True) }}'
    title: Bedroom temp
  - device_id: abeb25f8958c53d46423cf26bab07b82
    domain: mobile_app
    type: notify
    message: 'Bedroom temperature is: {{ states(''sensor.indoor_outdoor_meter_0c3f'',
      with_unit=True) }}'
    title: Bedroom temp
  mode: single
- id: '1720066244980'
  alias: Bedroom Humidity
  description: ''
  triggers:
  - type: humidity
    device_id: d873c8a3bfe858bf867ea8c1cd403123
    entity_id: 7b0b9fda0293b6991184ed0c7cb79bf9
    domain: sensor
    above: 55
    below: 40
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: device
  conditions: []
  actions:
  - device_id: a1bb718619b8daa06069ae464c493028
    domain: mobile_app
    type: notify
    message: Bedroom humidity no good!
  mode: single
- id: '1721191525838'
  alias: Guest Bathroom Hourly
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
  condition: []
  action:
  - type: turn_on
    device_id: cec6cf7b7945ee752fbbee055f301b57
    entity_id: 2e8a2e9950a01569e2f02fd808ec5ca7
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: cec6cf7b7945ee752fbbee055f301b57
    entity_id: 2e8a2e9950a01569e2f02fd808ec5ca7
    domain: switch
  mode: single
- id: '1725133021147'
  alias: Tag Pc Power is scanned
  description: Turns desktop pc on/off
  trigger:
  - platform: tag
    tag_id: f8ede390-72f3-4218-8a67-bed508ef695a
  condition: []
  action:
  - type: toggle
    device_id: d1c3c7c837d6e0ec4ea8daac5df9602f
    entity_id: deca49d3d36f83adf7ef904f8e72e6b8
    domain: switch
  mode: single
- id: '1726102989808'
  alias: Habit Tracker
  description: ''
  triggers:
  - tag_id: f641dd87-17bc-4a73-a16a-f070226344d9
    trigger: tag
  conditions: []
  actions:
  - action: rest_command.call_my_url
    data: {}
- id: '1726198529873'
  alias: Log Left
  description: ''
  trigger:
  - platform: tag
    tag_id: b6cd53c2-6889-4dd0-864b-031d3206ec3d
  condition: []
  action:
  - action: rest_command.left
    metadata: {}
    data: {}
  mode: single
- id: '1726198547865'
  alias: Log Right
  description: ''
  trigger:
  - platform: tag
    tag_id: f0df2b56-8c93-4d2f-ae5a-d6252e698305
  condition: []
  action:
  - action: rest_command.right
    metadata: {}
    data: {}
  mode: single
- id: '1727926100438'
  alias: Turn on garage light
  description: ''
  triggers:
  - type: opened
    device_id: fc2cc55d9b2c08a0aa6a88aa95b4ff1c
    entity_id: 1408d8ddd80c70bcedea6063d89b56ab
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - type: turn_on
    device_id: f0f00f1a6e402b8b8de574aa0ae7dd8a
    entity_id: 9d8ce1cfda7eb04301c07d84db1e4fa2
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: f0f00f1a6e402b8b8de574aa0ae7dd8a
    entity_id: 9d8ce1cfda7eb04301c07d84db1e4fa2
    domain: switch
  mode: single
- id: '1730091614332'
  alias: Cozy Bedroom
  description: ''
  triggers:
  - trigger: time
    at: 02:00:00
  conditions: []
  actions: []
  mode: single
- id: '1732237782329'
  alias: Fill the water
  description: ''
  triggers:
  - trigger: time_pattern
    seconds: '5'
  conditions:
  - type: is_value
    condition: device
    device_id: 477be90b1311ba44b4e9a76d72ba1acd
    entity_id: 3c15a7799a1f2847858e408e62f55bf1
    domain: sensor
    below: 1000
  actions:
  - repeat:
      sequence:
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.living_room_speaker
          message: Please fill the BRITA pitcher!
        target:
          entity_id: tts.google_en_com
      until:
      - type: is_value
        condition: device
        device_id: 477be90b1311ba44b4e9a76d72ba1acd
        entity_id: 3c15a7799a1f2847858e408e62f55bf1
        domain: sensor
        above: 1000
  mode: single
- id: '1738543546137'
  alias: Main Bathroom fan off after 10 mins
  description: ''
  triggers:
  - type: turned_on
    device_id: 935c8b1b4f1dea59836782088048a010
    entity_id: c8d8fff9184028eaa2c587d11df4f1ae
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 935c8b1b4f1dea59836782088048a010
    entity_id: c8d8fff9184028eaa2c587d11df4f1ae
    domain: switch
  mode: single
- id: '1738544305387'
  alias: Stairs 2 mins - Motion detection
  description: ''
  triggers:
  - type: motion
    device_id: fc2cc55d9b2c08a0aa6a88aa95b4ff1c
    entity_id: cb81bd0206e907c3b921fc6d11629a90
    domain: binary_sensor
    metadata:
      secondary: false
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - type: turn_on
    device_id: d9a69c3898b4a309509f2800abf53d0d
    entity_id: 29045bf1514d3c1eda019ca4216ddbbf
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: d9a69c3898b4a309509f2800abf53d0d
    entity_id: 29045bf1514d3c1eda019ca4216ddbbf
    domain: switch
  mode: single
- id: '1738546269690'
  alias: Control Bedroom Door Switch Based on Stairs and Sun
  description: ''
  triggers:
  - entity_id: switch.stairs
    trigger: state
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.stairs
        state: 'off'
      sequence:
      - entity_id: switch.bedroom_door_1
        action: switch.turn_on
    - conditions:
      - condition: state
        entity_id: switch.stairs
        state: 'on'
      sequence:
      - entity_id: switch.bedroom_door_1
        action: switch.turn_off
  mode: restart
- id: '1738546715466'
  alias: Sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - action: homeassistant.turn_off
    target:
      entity_id:
      - light.dining
      - switch.garage_light
      - switch.living_room_switch
      - switch.laundry_light
      - switch.bedroom_door_1
      - switch.main_bedroom
      - switch.basement
      - switch.backyard
      - switch.foyer
      - switch.hallway
      - switch.kitchen
      - switch.office
      - switch.porch
      - switch.stairs
    data: {}
  mode: single
- id: '1738592288281'
  alias: Lights for Şaziye
  description: ''
  triggers:
  - trigger: time
    at: 05:00:00
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - thu
    - sat
  actions:
  - type: turn_on
    device_id: f0259b2928ed4afd2bd13cc0e5aafe76
    entity_id: 9d02d2e3d1fd55c55913f9ad18878c2b
    domain: switch
  - type: turn_on
    device_id: 5bba9fa140449f4805bf899bd2c8032c
    entity_id: 688954b54c233e24865b176f42d73890
    domain: switch
  - type: turn_on
    device_id: b667a4b95f88cbea5e7831d334b4041b
    entity_id: b41d1896e7a284447690d37c82086423
    domain: switch
  - delay:
      hours: 0
      minutes: 50
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: f0259b2928ed4afd2bd13cc0e5aafe76
    entity_id: 9d02d2e3d1fd55c55913f9ad18878c2b
    domain: switch
  - type: turn_off
    device_id: 5bba9fa140449f4805bf899bd2c8032c
    entity_id: 688954b54c233e24865b176f42d73890
    domain: switch
  - type: turn_off
    device_id: b667a4b95f88cbea5e7831d334b4041b
    entity_id: b41d1896e7a284447690d37c82086423
    domain: switch
  mode: single
- id: '1738800420967'
  alias: Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - type: turn_on
    device_id: 400441e7f95777efa9c66352a2b7f3ca
    entity_id: eb5d56eff8ad8ae54642d1dc759fff34
    domain: switch
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      entity_id:
      - cover.backyard_left_curtain
  mode: single
- id: '1739467074410'
  alias: Purifier and Humidifier Conflict Prevention
  description: ''
  triggers:
  - type: turned_on
    device_id: 7750a34c7a952223cf3c9d53cfb90972
    entity_id: 09664482b566d5f79f80b4f641d961a3
    domain: fan
    trigger: device
  - type: turned_on
    device_id: 71c17d1d8bb287945542339a8365c80a
    entity_id: 1458dbc7ad1004c4335253c9ea6d57b3
    domain: humidifier
    trigger: device
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: fan.living_room_purifier_fan
        state: 'on'
      sequence:
      - type: turn_off
        device_id: 71c17d1d8bb287945542339a8365c80a
        entity_id: 1458dbc7ad1004c4335253c9ea6d57b3
        domain: humidifier
    - conditions:
      - condition: state
        entity_id: humidifier.humidifier
        state: 'on'
      sequence:
      - type: turn_off
        device_id: 7750a34c7a952223cf3c9d53cfb90972
        entity_id: 09664482b566d5f79f80b4f641d961a3
        domain: fan
  mode: restart
- id: '1740106883671'
  alias: Limit laundry fan running time to 10 mins
  description: ''
  triggers:
  - type: turned_on
    device_id: 2805780ce9262ab1a4895e41267752b6
    entity_id: 00d756a6ca1a6266f7d0104b51d2895b
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: 2805780ce9262ab1a4895e41267752b6
    entity_id: 00d756a6ca1a6266f7d0104b51d2895b
    domain: switch
  mode: single
- id: '1741485290540'
  alias: Forgot the cats!
  description: ''
  triggers:
  - type: turned_on
    device_id: fccb855464dbcebde8a160334aaf4eed
    entity_id: 9acbfae6eb3677f6f874af8d825a8626
    domain: switch
    trigger: device
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.living_room_speaker
      message: You forgot about the cats, please let them out!
  mode: single
